version: '3.9'

services:
  envanter:
    build: .
    ports:
      - "${HOST_PORT:-5000}:5000"
    environment:
      - DB_FILE=./data/envanter.db
    volumes:
      - ./data:/app/data
      - ./image:/app/image     # hosttaki image klasörünü container’a bağla
